### ISSUE TITLE
deepmatch execcutable

### ISSUE THREAD

**Issue by sushilks** [pathak22/videoseg#2]
The code refers to running executable "deeplearning/dpathak/video-processing/deepmatch/deepmatch"
Where can I find this?

**Comment by sushilks** [comment]
Is it this package "http://lear.inrialpes.fr/src/deepmatching/"

**Comment by pathak22** [comment]
Yes. However, I would like to note that I am only providing this implementation of the video-tracker using deepmatch only to be used as a guidance. It is not optimized at all. It works ok, not great. I did not use it in our CVPR17 paper, but just developed it as part of the project.

Video segmentation code is fine, and was used in our CVPR17 paper
